# Generated by Django 4.2.6 on 2024-01-03 07:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('homeHeader', wagtail.fields.StreamField([('header_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('desc', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Company Description', required=True)), ('images', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, use_json_field=True)),
                ('bodyHeader', wagtail.fields.StreamField([('body_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('desc', wagtail.blocks.RichTextBlock(features=['bold', 'italic'])), ('images', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, use_json_field=True)),
                ('navHeader', wagtail.fields.StreamField([('nav_block', wagtail.blocks.StructBlock([('head_nav', wagtail.blocks.CharBlock(max_length=25, required=True)), ('about_nav', wagtail.blocks.CharBlock(max_length=25, required=True)), ('proj_nav', wagtail.blocks.CharBlock(max_length=25, required=True)), ('contact_nav', wagtail.blocks.CharBlock(max_length=25, required=True))]))], blank=True, use_json_field=True)),
                ('contentBlock', wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('content_title', wagtail.blocks.CharBlock(help_text='Project name', max_length=15, required=True)), ('content_bod', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Project Description', required=True)), ('content_image_block', wagtail.images.blocks.ImageChooserBlock(required=True)), ('content_checkbox_block', wagtail.blocks.BooleanBlock(help_text='To be highligthed', required=False))]))], blank=True, use_json_field=True)),
            ],
            options={
                'verbose_name': 'homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
